accounts/urls.py
from django.urls import path

from accounts.views import (
    RegisterView,
    ProfileView,
    UpdateProfileView,
    CommunityListView,
    UserConnectView,
    UserConnectApproveView,
    UserConnectRejectView,
    UserUkConnectView,
    UserConnectBlockView,
    UserConnectUnblockView,
    DeleteProfileView,
)

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register"),
    path(
        "profile_page/<int:pk>/",
        ProfileView.as_view(),
        name="profile-page"),
    path(
        "profile_page/<int:pk>/update/",
        UpdateProfileView.as_view(),
        name="profile-update",
    ),
    path(
        "delete_profile/<int:pk>/",
        DeleteProfileView.as_view(),
        name="profile-delete"
    ),
    path("community/",
         CommunityListView.as_view(),
         name="community-list"),
    path("connect/<int:user_id>/",
         UserConnectView.as_view(),
         name="user-connect"),
    path(
        "aprove-connect/<int:connection_id>/",
        UserConnectApproveView.as_view(),
        name="approve-connect",
    ),
    path(
        "reject-connect/<int:connection_id>/",
        UserConnectRejectView.as_view(),
        name="reject-connect",
    ),
    path(
        "block-connect/<int:connection_id>/",
        UserConnectBlockView.as_view(),
        name="block-connect",
    ),
    path(
        "unblock-connect/<int:connection_id>/",
        UserConnectUnblockView.as_view(),
        name="unblock-connect",
    ),
    path(
        "uk-invite/<str:invite_type>/<int:sender_id>/",
        UserUkConnectView.as_view(),
        name="user-invite-uk",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("dashboard.urls"), name="dashboard"),
    path("events/", include("events.urls"), name="events"),
    path("finances/", include("finances.urls"), name="finances"),
    path("groups/", include("groups.urls"), name="groups"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

events/urls.py
from django.urls import path

from events.views import (
    EventHeroView,
    EventCreateView,
    EventDetailView,
    EventDeleteView,
    EventAddMembersView,
    EventAcceptInviteView,
    EventRejectMembersView,
    EventUpdateMembersView,
    EventLeaveView,
    EventUpdateView,
)

urlpatterns = [
    path("", EventHeroView.as_view(), name="event-hero"),
    path("create/", EventCreateView.as_view(), name="private-event-create"),
    path("<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("<int:pk>/update/", EventUpdateView.as_view(), name="event-update"),
    path("<int:pk>/delete/", EventDeleteView.as_view(), name="event-delete"),
    path(
        "<int:pk>/members/add/<int:user_id>/",
        EventAddMembersView.as_view(),
        name="event-add-members",
    ),
    path(
        "<int:pk>/accept-invite/",
        EventAcceptInviteView.as_view(),
        name="event-accept-members",
    ),
    path(
        "<int:pk>/reject-members/<int:user_id>/<str:stay>/",
        EventRejectMembersView.as_view(),
        name="event-reject-members",
    ),
    path(
        "<int:pk>/update-members/<int:user_id>/",
        EventUpdateMembersView.as_view(),
        name="event-promote-members",
    ),
    path(
        "<int:pk>/leave-event/",
        EventLeaveView.as_view(),
        name="event-leave"
    ),
]

app_name = "events"

groups/urls.py
from django.urls import path

from groups.views import (
    GroupsHomeView,
    GroupCreateView,
    GroupDetailView,
    GroupDeleteView,
    GroupInviteMemberView,
    GroupAcceptInviteView,
    GroupRejectInviteView,
    GroupPromoteView,
    GroupDemoteView,
    LeaveGroupView,
    GroupEditView,
    GroupEventsCreateView,
)

urlpatterns = [
    path("", GroupsHomeView.as_view(), name="home"),
    path("create-group/", GroupCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", GroupDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", GroupEditView.as_view(), name="update"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete"),
    path(
        "<int:pk>/invite-member/<int:user_id>/",
        GroupInviteMemberView.as_view(),
        name="invite-member",
    ),
    path(
        "<int:pk>/accept-invite/<int:user_id>/",
        GroupAcceptInviteView.as_view(),
        name="accept-invite",
    ),
    path(
        "<int:pk>/reject-invite/<int:user_id>/<str:stay>/",
        GroupRejectInviteView.as_view(),
        name="reject-invite",
    ),
    path(
        "<int:pk>/promote/<int:user_id>/",
        GroupPromoteView.as_view(),
        name="promote"),
    path(
        "<int:pk>/demote/<int:user_id>/",
        GroupDemoteView.as_view(),
        name="demote"),
    path(
        "leave-group/<int:group_id>/",
        LeaveGroupView.as_view(),
        name="leave-group"),
    path(
        "<int:group_id>/create-event//",
        GroupEventsCreateView.as_view(),
        name="create-inside-event",
    ),
]

app_name = "groups"

accounts/forms.py
from urllib import request

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import Currency

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
        ]

    username = forms.CharField(
        max_length=255, widget=forms.TextInput(
            attrs={"placeholder": "Username"})
    )

    email = forms.EmailField(
        max_length=255, widget=forms.EmailInput(
            attrs={"placeholder": "Email"})
    )

    first_name = forms.CharField(
        max_length=255, widget=forms.TextInput(
            attrs={"placeholder": "First name"})
    )

    last_name = forms.CharField(
        max_length=255, widget=forms.TextInput(
            attrs={"placeholder": "Last name"})
    )

    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput(
            attrs={"placeholder": "Password"})
    )

    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={"placeholder": "Repeat password"}),
    )

    def clean_username(self) -> str:
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username


class UserUpdateForm(forms.ModelForm):
    default_currency = forms.ChoiceField(
        choices=Currency.choices,
        widget=forms.Select(
            attrs={
                "class": "form-select",
                "placeholder": "Currency (UAH, USD, EUR...)"
            }
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "job",
            "salary",
            "default_currency",
        ]


class UserKeyConnectForm(forms.Form):
    unik_key = forms.CharField(max_length=255, label="Unique key")

accounts/views.py
from typing import Any

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q, QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    ListView,
    DeleteView,
)

from accounts.forms import (
    UserRegisterForm,
    UserUpdateForm,
    UserKeyConnectForm
)
from accounts.models import UserConnection
from accounts.services.receive_connection import UserConnectionsService
from accounts.services.user_budget_service import UserBudgetService
from accounts.services.user_connection_control import UserInvitationService
from events.models import Event
from events.services.event_invitation import EventInvitationService
from finances.forms import TopUpBudgetForm
from finances.models import Budget, Category
from groups.models import Group
from groups.services.group_invitation import GroupInvitationService


class RegisterView(CreateView):
    template_name = "registration/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
            "Registration successful. Please log in.",
            extra_tags="registration",
        )
        return redirect(self.success_url)


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "profile/profile_detail.html"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.object

        user_budget = user.budget

        context["transaction_history"] = (
            user_budget.transactions
            .select_related("category", "payer")
            .order_by("-date", "-timestamp_create")[:15]
        )

        context["current_budget"] = user_budget.get_budget_data()

        context["events"] = (
            Event.objects.filter(
                Q(creator=user) | Q(memberships__user=user)
            )
            .select_related("creator")
            .prefetch_related("memberships__user")
            .distinct()
        )

        context["groups"] = (
            Group.objects.filter(
                Q(creator=user) | Q(memberships__user=user)
            )
            .select_related("creator")
            .prefetch_related("memberships__user")
            .distinct()
        )

        context["take_to_connect"] = (
            UserConnection.objects.filter(
                from_user=user,
                status=UserConnection.Status.PENDING
            )
            .select_related("to_user")
        )

        context["invite_to_connect"] = (
            UserConnection.objects.filter(
                to_user=user,
                status=UserConnection.Status.PENDING
            )
            .select_related("from_user")
        )

        context["connections"] = UserConnectionsService.get_user_connections(
            user.id,
            "accepted"
        )

        categories = list(
            Category.objects.filter(is_active=True)
            .order_by("order_index", "name")
        )

        context["categories_income"] = [
            c for c in categories if c.category_type == Category.Types.INCOME
        ]
        context["categories_expense"] = [
            c for c in categories if c.category_type == Category.Types.EXPENSE
        ]

        context["top_up_form"] = TopUpBudgetForm()

        return context


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = "profile/update_form.html"

    def get_success_url(self) -> str:
        return reverse_lazy("profile-page", kwargs={"pk": self.object.pk})


class DeleteProfileView(LoginRequiredMixin, DeleteView):
    model = get_user_model()
    template_name = "profile/user_confirm_delete.html"
    success_url = reverse_lazy("login")

    def delete(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.object = self.get_object()
        messages.success(
            request,
            "Profile has been deleted. Please log in.",
            extra_tags="registration",
        )
        UserBudgetService.delete_user_budget(self.object)
        return super().delete(request, *args, **kwargs)


class CommunityListView(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = "community/community_list.html"
    context_object_name = "other_users"

    def get_template_names(self) -> str:
        if self.request.headers.get("HX-Request"):
            return "partials/user_table_rows.html"
        return self.template_name

    def get_queryset(self) -> QuerySet[UserConnection]:
        query = self.request.GET.get("q", "")
        self.request.GET.get("status", "")

        connections = UserConnectionsService.get_user_connections(
            self.request.user.id)
        connected_ids = [
            c.from_user_id
            if c.to_user_id == self.request.user.id else c.to_user_id
            for c in connections
        ]
        connected_ids.append(self.request.user.id)

        queryset = get_user_model().objects.exclude(id__in=connected_ids)

        if query:
            queryset = queryset.filter(
                Q(username__icontains=query)
                | Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
            )
        return queryset

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        query = self.request.GET.get("q", "")
        status_filter = self.request.GET.get("status", "")

        connections = UserConnectionsService.get_user_connections(
            user_id=self.request.user.id,
            status=status_filter or None,
            query=query or None,
        )

        context["user_connections"] = connections
        context["status_choices"] = UserConnection.Status.choices
        context["uniq_key_form"] = UserKeyConnectForm()
        context["content_type"] = "connection"
        context["object_id"] = self.request.user.id

        return context


class UserConnectView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, user_id: int) -> HttpResponse:
        recipient = get_object_or_404(get_user_model(), pk=user_id)

        if recipient == request.user:
            return redirect("community-list")

        UserInvitationService.invite_user_to_connect(
            sender=request.user,
            recipient=recipient
        )

        return redirect(request.META.get("HTTP_REFERER", "community-list"))


class UserConnectApproveView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, connection_id: int) -> HttpResponse:
        UserInvitationService.approve_user_to_connect(
            connection_id=connection_id
        )
        return redirect(request.META.get("HTTP_REFERER", "/"))


class UserConnectRejectView(LoginRequiredMixin, View):
    def post(self, request:HttpRequest, connection_id: int) -> HttpResponse:
        UserInvitationService.reject_user_to_connect(
            connection_id=connection_id
        )

        return redirect(request.META.get("HTTP_REFERER", "profile-dashboard"))


class UserConnectBlockView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, connection_id: int) -> HttpResponse:
        UserInvitationService.block_user_to_connect(
            connection_id=connection_id
        )

        return redirect(request.META.get("HTTP_REFERER", "profile-dashboard"))


class UserConnectUnblockView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, connection_id: int) -> HttpResponse:
        UserInvitationService.un_block_user_connect(
            connection_id=connection_id
        )

        return redirect(
            request.META.get("HTTP_REFERER", "profile-dashboard")
        )


class UserUkConnectView(LoginRequiredMixin, View):
    def post(
            self,
            request: HttpRequest,
            invite_type: str,
            sender_id: int
    ) -> HttpResponse:
        form = UserKeyConnectForm(request.POST)

        if not form.is_valid():
            messages.error(
                request,
                "Invalid key format",
                extra_tags="community"
            )
            return redirect(request.META.get("HTTP_REFERER"))

        unik_key = form.data.get("unik_key")

        try:
            recipient = UserConnectionsService.get_user_from_uk(
                unik_key
            )
            if invite_type == "connection":
                UserInvitationService.invite_user_to_connect(
                    sender=request.user,
                    recipient=recipient
                )
            elif invite_type == "event":
                EventInvitationService.create_event_invitation(
                    list_of_connects=[
                        recipient.id,
                    ],
                    event_id=sender_id,
                )
            elif invite_type == "group":
                GroupInvitationService.create_group_invitation(
                    list_of_connects=[
                        recipient.id,
                    ],
                    group_id=sender_id,
                )
            messages.success(
                request, "Connection request sent successfully.",
                extra_tags="community"
            )
        except ValidationError as e:
            messages.error(request, e.message, extra_tags="community")
        except get_user_model().DoesNotExist:
            messages.error(request,
                           "User not found.",

accounts/templates/profile/components/budget_section.html
<h3>Budget info..</h3>
{% if current_budget %}
  <p>Current amount stayed: {{ current_budget.current_amount }}</p>
  <p>Total income: {{ current_budget.total_income }}</p>
  <p>Total expenses:{{ current_budget.total_expenses }}</p>
{% endif %}

accounts/templates/profile/components/events_list.html
<div>
  <h3 class="mb-3">My events</h3>
  <ul class="d-flex flex-column gap-2 list-group">
    {% for event in events|slice:":4" %}

      <li class="list-group-item list-group-item-dark">
        <a style="text-decoration: none"
           href="{% url "events:event-detail" pk=event.id %}"
           class="text-dark">
          {{ event.name }} — {{ event.status }} —
          {{ event.planned_amount }}
        </a>
      </li>

    {% endfor %}
  </ul>
  {% if events|length > 4 %}
    <a href="{% url 'events:event-hero' %}"
       class="small text-white mt-2 d-inline-block">
      View all →
    </a>
  {% endif %}

</div>

accounts/templates/profile/components/group_list.html
<div class="mb-3">
  <h3 class="mb-3 mt-5">My Groups</h3>
  <ul class="d-flex flex-column gap-2 list-group">
    {% for group in groups|slice:":4" %}
      <li class="list-group-item list-group-item-dark">
        <a style="text-decoration: none"
           href="{% url "groups:detail" pk=group.id %}"
           class="text-dark">
          {{ group.name }} — {{ group.state }} —
          {{ group.budget.current_amount }}
        </a>
      </li>
    {% endfor %}
  </ul>
  {% if groups|length > 4 %}
    <a href="{% url 'groups:home' %}"
       class="small text-white mt-2 d-inline-block">
      View all →
    </a>
  {% endif %}
</div>

accounts/templates/profile/components/list_of_conecctions.html
<div class="mb-3">
  <h3 class="mb-3 mt-5">My connections</h3>
  <ul class="d-flex flex-column gap-2 list-group">
    {% for connection in connections|slice:":4" %}
      <li class="d-flex flex-row align-center justify-content-between list-group-item list-group-item-dark">
        <p class="text-dark">
          {% if connection.from_user.id == user.id %}
            {{ connection.to_user.username }}
            ({{ connection.to_user.first_name }}
            {{ connection.to_user.last_name }})
          {% else %}
            {{ connection.from_user.username }}
            ({{ connection.from_user.first_name }}
            {{ connection.from_user.last_name }})
          {% endif %}
        </p>
        <form method="post"
              action="{% url 'reject-connect' connection.id %}">
          {% csrf_token %}
          <button class="btn btn-danger">
            Delete
          </button>
        </form>
      </li>
    {% endfor %}
  </ul>
  {% if connections|length > 4 %}
    <a href="{% url 'community-list' %}"
       class="small text-white mt-2 d-inline-block">
      View all →
    </a>
  {% endif %}
</div>

accounts/templates/profile/components/list_of_invitations.html
<div class="mb-3">
  <h5 class="text-white">
    <strong>Invitation</strong>
  </h5>
  <ul class="d-flex flex-column gap-2 list-group">
    {% for connect in take_to_connect|slice:":2" %}
      <li class="d-flex flex-row align-center justify-content-between list-group-item list-group-item-dark">
        <p class="text-dark text-center mb-0">
          Sent to:<strong> {{ connect.to_user.username }}</strong>
          - {{ connect.status }}
        </p>
        <form method="post"
              action="{% url 'reject-connect' connect.id %}">
          {% csrf_token %}
          <button class="btn btn-danger">
            Refuse
          </button>
        </form>
      </li>
    {% endfor %}
    {% for invite in invite_to_connect|slice:":3" %}
      <li class="d-flex flex-row align-items-center align-center justify-content-between list-group-item list-group-item-dark">
        <p class="text-dark text-center mb-0">
          Receive from:<strong> {{ invite.from_user.username }}</strong>
          - {{ invite.status }}
        </p>
        <form method="post"
              action="{% url 'approve-connect' invite.id %}">
          {% csrf_token %}
          <button class="btn btn-success">
            Approve
          </button>
        </form>
        <form method="post"
              action="{% url 'reject-connect' invite.id %}">
          {% csrf_token %}
          <button class="btn btn-danger">
            Reject
          </button>
        </form>
        <form method="post"
              action="{% url 'reject-connect' invite.id %}">
          {% csrf_token %}
          <button class="btn btn-danger">
            Block
          </button>
        </form>
      </li>
    {% endfor %}
  </ul>
  {% if take_to_connect|length > 2 or invite_to_connect|length > 3 %}
    <a href="{% url 'community-list' %}"
       class="small text-white mt-2 d-inline-block">
      View all →
    </a>
  {% endif %}
</div>

accounts/templates/profile/components/top_of_profile.html
{% load static %}
<div
    class="p-4 bg-transparent text-white rounded flex-column justify-content-between">
  <div class="d-flex align-items-center mb-4">
    <img src="{% static 'assets/images/profile-svg-white.svg' %}"
         class="me-3"
         alt="User avatar"
         width="64" height="64">
    <div class="flex flex-column justify-content-start">
      <h2 class="mb-0 flex flex-column justify-content-start">
        {{ user.first_name }} {{ user.last_name }}
      </h2>
      <span
          class="d-block text-start text-secondary">@{{ user.username }}
              </span>
      <span class="d-block text-start text-secondary">
                Unique number: <strong
          class="text-white">{{ user.get_user_uniq_key }}</strong>
              </span>
    </div>
    <div>
      <a href="{% url 'profile-update' pk=object.id %}"
         class="btn btn-primary d-inline-flex align-items-center gap-2"
         role="button">
        <svg
            width="24px" height="24px"
            viewBox="0 0 24 24" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
          <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
          <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
             stroke-linejoin="round" stroke="currentColor"
             stroke-width="0.096"></g>
          <g id="SVGRepo_iconCarrier">
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M21.1213 2.70705C19.9497 1.53548 18.0503 1.53547 16.8787 2.70705L15.1989 4.38685L7.29289 12.2928C7.16473 12.421 7.07382 12.5816 7.02986 12.7574L6.02986 16.7574C5.94466 17.0982 6.04451 17.4587 6.29289 17.707C6.54127 17.9554 6.90176 18.0553 7.24254 17.9701L11.2425 16.9701C11.4184 16.9261 11.5789 16.8352 11.7071 16.707L19.5556 8.85857L21.2929 7.12126C22.4645 5.94969 22.4645 4.05019 21.2929 2.87862L21.1213 2.70705ZM18.2929 4.12126C18.6834 3.73074 19.3166 3.73074 19.7071 4.12126L19.8787 4.29283C20.2692 4.68336 20.2692 5.31653 19.8787 5.70705L18.8622 6.72357L17.3068 5.10738L18.2929 4.12126ZM15.8923 6.52185L17.4477 8.13804L10.4888 15.097L8.37437 15.6256L8.90296 13.5112L15.8923 6.52185ZM4 7.99994C4 7.44766 4.44772 6.99994 5 6.99994H10C10.5523 6.99994 11 6.55223 11 5.99994C11 5.44766 10.5523 4.99994 10 4.99994H5C3.34315 4.99994 2 6.34309 2 7.99994V18.9999C2 20.6568 3.34315 21.9999 5 21.9999H16C17.6569 21.9999 19 20.6568 19 18.9999V13.9999C19 13.4477 18.5523 12.9999 18 12.9999C17.4477 12.9999 17 13.4477 17 13.9999V18.9999C17 19.5522 16.5523 19.9999 16 19.9999H5C4.44772 19.9999 4 19.5522 4 18.9999V7.99994Z"
                  fill="currentColor"></path>
          </g>
        </svg>

      </a>

      <a href="{% url "profile-delete" pk=user.id %}"
         class="btn btn-danger d-inline-flex align-items-center gap-2">

        <svg fill="currentColor" width="24px" height="24px"
             xmlns="http://www.w3.org/2000/svg"
             viewBox="0 0 24 24">
          <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
          <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
             stroke-linejoin="round"></g>
          <g id="SVGRepo_iconCarrier">
            <path
                d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zm2.46-7.12l1.41-1.41L12 12.59l2.12-2.12 1.41 1.41L13.41 14l2.12 2.12-1.41 1.41L12 15.41l-2.12 2.12-1.41-1.41L10.59 14l-2.13-2.12zM15.5 4l-1-1h-5l-1 1H5v2h14V4z"></path>
          </g>
        </svg>
      </a>
    </div>
  </div>
  <!-- BUTTONS -->
  <div class="mt-4 d-flex gap-3 flex-wrap justify-content-center">
    <button
        class="btn btn-primary d-inline-flex align-items-center gap-2"
        data-bs-toggle="modal"
        data-bs-target="#topUpModal">
      <svg
          width="46px" height="46px"
          fill="currentColor" viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg">
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
           stroke-linejoin="round"></g>
        <g id="SVGRepo_iconCarrier">
          <path
              d="M22,4V5H5A1,1,0,0,0,5,7H21a1,1,0,0,1,1,1V19a2,2,0,0,1-2,2H13V14.414l1.293,1.293a1,1,0,0,0,1.414-1.414l-3-3a1,1,0,0,0-1.416,0l-3,3a1,1,0,0,0,1.414,1.414L11,14.414V21H4a2,2,0,0,1-2-2V5A2,2,0,0,1,4,3H21A1,1,0,0,1,22,4Z"></path>
        </g>
      </svg>
      <span>Top up balance</span>
    </button>

    <button
        class="btn btn-warning d-inline-flex align-items-center gap-2"
        data-bs-toggle="modal"
        data-bs-target="#setExpenseModal">
      <svg
          width="46px" height="46px"
          fill="currentColor" viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg">
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
           stroke-linejoin="round"></g>
        <g id="SVGRepo_iconCarrier">
          <path
              d="M22,4V5H5A1,1,0,0,0,5,7H21a1,1,0,0,1,1,1V19a2,2,0,0,1-2,2H13V14.414l1.293,1.293a1,1,0,0,0,1.414-1.414l-3-3a1,1,0,0,0-1.416,0l-3,3a1,1,0,0,0,1.414,1.414L11,14.414V21H4a2,2,0,0,1-2-2V5A2,2,0,0,1,4,3H21A1,1,0,0,1,22,4Z"></path>
        </g>
      </svg>
      <span>Set up expense</span>
    </button>
  </div>
</div>

accounts/templates/profile/components/transaction_history.html
<h3>Transaction history</h3>
{% for transaction in transaction_history|slice:":10" %}
  <p>{{ transaction.get_short_description }}</p>
{% endfor %}
{% if transaction_history|length > 10 %}
  <a href="{% url "transfer-history" target="user" pk=user.id %}">Show
    all</a>
{% endif %}

accounts/templates/profile/components/user_info.html
<ul class="list-group list-group-flush ">
  <li class="list-group-item bg-dark text-white align-items-lg-start">
    <strong>Full name:</strong> {{ object }}
  </li>

  <li class="list-group-item bg-dark text-white">
    <strong>Email:</strong> {{ object.email }}
  </li>

  <li class="list-group-item bg-dark text-white">
    <strong>Job:</strong> {{ object.job|default:"—" }}
  </li>

  <li class="list-group-item bg-dark text-white">
    <strong>Salary:</strong> {{ object.salary }} {{ object.default_currency }}
  </li>

  <li class="list-group-item bg-dark text-white">
    <strong>Default Currency:</strong> {{ object.default_currency }}
  </li>
</ul>