config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("dashboard.urls"), name="dashboard"),
    path("events/", include("events.urls"), name="events"),
    path("finances/", include("finances.urls"), name="finances"),
    path("groups/", include("groups.urls"), name="groups"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

groups/urls.py
from django.urls import path

from groups.views import (
    GroupsHomeView,
    GroupCreateView,
    GroupDetailView,
    GroupDeleteView,
    GroupInviteMemberView,
    GroupAcceptInviteView,
    GroupRejectInviteView,
    GroupPromoteView,
    GroupDemoteView,
    LeaveGroupView,
    GroupEditView,
    GroupEventsCreateView,
)

urlpatterns = [
    path("", GroupsHomeView.as_view(), name="home"),
    path("create-group/", GroupCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", GroupDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", GroupEditView.as_view(), name="update"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete"),
    path(
        "<int:pk>/invite-member/<int:user_id>/",
        GroupInviteMemberView.as_view(),
        name="invite-member",
    ),
    path(
        "<int:pk>/accept-invite/<int:user_id>/",
        GroupAcceptInviteView.as_view(),
        name="accept-invite",
    ),
    path(
        "<int:pk>/reject-invite/<int:user_id>/<str:stay>/",
        GroupRejectInviteView.as_view(),
        name="reject-invite",
    ),
    path(
        "<int:pk>/promote/<int:user_id>/",
        GroupPromoteView.as_view(),
        name="promote"),
    path(
        "<int:pk>/demote/<int:user_id>/",
        GroupDemoteView.as_view(),
        name="demote"),
    path(
        "leave-group/<int:group_id>/",
        LeaveGroupView.as_view(),
        name="leave-group"),
    path(
        "<int:group_id>/create-event//",
        GroupEventsCreateView.as_view(),
        name="create-inside-event",
    ),
]

app_name = "groups"

groups/models.py
from functools import cached_property

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from addition_info.choise_models import Role, Status

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from events.models import Event
from finances.models import Budget


class Group(models.Model):
    class States(models.TextChoices):
        PERMANENT = "Permanent"
        TEMPORARY = "Temporary"

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    state = models.CharField(
        max_length=20,
        choices=States.choices,
        default=States.PERMANENT,
    )
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="group_creator",
    )
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)
    budgets = GenericRelation(Budget)

    class Meta:
        db_table = "a_groups"

    def __str__(self):
        return f"{self.name} ({self.state})"

    def clean(self) -> None:
        if self.state == self.States.PERMANENT:
            if self.start_date or self.end_date:
                raise ValidationError(
                    "Permanent groups must not have start/end dates.")
        else:
            if (
                    self.start_date
                    and self.end_date
                    and self.end_date < self.start_date
            ):
                raise ValidationError("end_date must be >= start_date.")

    @cached_property
    def budget(self) -> Budget:
        """
        Return the Budget instance for this User, or None.
        Expects at most one Budget due to unique constraint in Budget.meta.
        """
        ct = ContentType.objects.get_for_model(self)
        return Budget.objects.filter(
            content_type=ct,
            object_id=self.id
        ).first()


class GroupMembership(models.Model):
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name="memberships",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="group_memberships",
    )
    role = models.CharField(
        max_length=20,
        choices=Role.choices,
        default=Role.MEMBER,
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    join_date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = "group_membership"
        constraints = [
            models.UniqueConstraint(
                fields=["group", "user"],
                name="unique_group_user",
            )
        ]


class GroupEventConnection(models.Model):
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name="event_link",
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="group_link",
    )
    join_date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = "group_event_connections"
        constraints = [
            models.UniqueConstraint(
                fields=["group", "event"],
                name="unique_group_event",
            )
        ]

    def get_related_events(self) -> str:
        return (
            f"{self.event.name} ({self.event.event_type} "
            f"- {self.event.status}) - {self.join_date}"
        )

groups/views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpRequest, HttpResponseBase
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    DeleteView,
)

from accounts.services.receive_connection import UserConnectionsService
from addition_info.choise_models import Status, Role
from dashboard.services.group_stats import GroupStatsService
from events.models import Event
from finances.custom_mixins import SuccessUrlFromNextMixin
from finances.forms import TransferCreateForm, BudgetEditForm
from groups.forms import GroupCreateForm, GroupEditForm, GroupEventCreateForm
from groups.models import Group, GroupMembership
from groups.services.group_event_service import GroupEventService
from groups.services.group_invitation import GroupInvitationService


class GroupsHomeView(LoginRequiredMixin, TemplateView):
    template_name = "groups-home.html"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.request.user
        groups = Group.objects.filter(
            Q(creator=user)
            | Q(memberships__user=user, memberships__status=Status.ACCEPTED)
        ).distinct()
        context["groups"] = groups

        context["invites"] = GroupMembership.objects.filter(
            user_id=user.id,
            status=Status.PENDING,
        )
        return context


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    success_url = reverse_lazy("groups:home")

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form) -> HttpResponse:
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        self.object.save()

        GroupMembership.objects.create(
            group=self.object,
            user=self.request.user,
            status=Status.ACCEPTED,
            role=Role.CREATOR,
        )

        participants_ids = form.cleaned_data["participants"]

        GroupInvitationService.create_group_invitation(
            list_of_connects=participants_ids, group_id=self.object.id
        )

        return super().form_valid(form)


class GroupDetailView(LoginRequiredMixin, SuccessUrlFromNextMixin, DetailView):
    model = Group

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        group = self.object
        user = self.request.user

        members_qs = GroupMembership.objects.filter(
            group=group
        ).select_related("user")

        member_ids = set(members_qs.values_list("user_id", flat=True))

        user_membership = next((
            member
            for member in members_qs
            if member.user_id == user.id),
            None
        )
        user_role = user_membership.role if user_membership else None

        potential_invites = [
            connect.other_user(user)
            for connect in UserConnectionsService.get_user_connections(
                user.id,
                "accepted"
            )
            if connect.other_user(user).id not in member_ids
        ]

        try:
            budget = group.budget
            context["current_budget"] = budget.get_budget_data()
            context[
                "transaction_history"] = budget.transactions.select_related(
                "category", "payer"
            ).all()
        except AttributeError:
            context["current_budget"] = None
            context["transaction_history"] = []

        delete_permission = "Creator" if group.creator_id else "Admin"
        bar_cart_data = GroupStatsService.get_bar_chart_data(
            pk=group.id
        )

        context.update({
            "related_events": GroupEventService.get_events_for_group(
                group_id=group.id
            ),
            "delete_permission": delete_permission,
            "transaction_form": TransferCreateForm(),
            "content_type": "group",
            "object_id": group.id,
            "user_role": user_role,
            "connects": potential_invites,
            "members": members_qs,
            "chart_data": bar_cart_data,
        })

        return context


class GroupEditView(LoginRequiredMixin, View):
    template_name = "groups/group_update.html"

    def get(self, request: HttpRequest, pk: int) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)
        budget = group.budget

        return render(
            request,
            self.template_name,
            {
                "group_form": GroupEditForm(instance=group),
                "budget_form": BudgetEditForm(instance=budget),
                "group": group,
            },
        )

    @transaction.atomic
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)
        budget = group.budget

        group_form = GroupEditForm(request.POST, instance=group)
        budget_form = BudgetEditForm(request.POST, instance=budget)

        if group_form.is_valid() and budget_form.is_valid():
            group_form.save()
            budget_form.save()
            budget.recalc()
            return redirect("groups:detail", pk=pk)

        return render(
            request,
            self.template_name,
            {
                "group_form": group_form,
                "budget_form": budget_form,
                "group": group,
            },
        )


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy("groups:home")


class GroupInviteMemberView(LoginRequiredMixin, View):
    def post(
            self,
            request: HttpRequest,
            pk: int,
            user_id: int
    ) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)

        GroupInvitationService.create_group_invitation(
            group_id=group.id,
            list_of_connects=[
                user_id,
            ],
        )
        return redirect("groups:detail", pk=pk)


class GroupAcceptInviteView(LoginRequiredMixin, View):
    def post(
            self,
            request: HttpRequest,
            pk: int,
            user_id: int
    ) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)

        GroupInvitationService.accept_group_invitation(
            group_id=group.id,
            user_id=user_id
        )
        return redirect("groups:home")


class GroupRejectInviteView(LoginRequiredMixin, View):
    def post(
            self,
            request: HttpRequest,
            pk: int,
            user_id: int,
            stay: str
    ) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)

        GroupInvitationService.reject_group_invitation(
            group_id=group.id,
            user_id=user_id
        )

        if stay == "inside":
            return redirect("groups:detail", pk=pk)
        else:
            return redirect("groups:home")


class GroupPromoteView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int,
             user_id: int) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)

        GroupInvitationService.promote_group_member(
            group_id=group.id,
            user_id=user_id
        )
        return redirect("groups:detail", pk=pk)


class GroupDemoteView(LoginRequiredMixin, View):
    def post(
            self,
            request: HttpRequest,
            pk: int,
            user_id: int
    ) -> HttpResponse:
        group = get_object_or_404(Group, pk=pk)

        GroupInvitationService.demote_group_member(
            group_id=group.id,
            user_id=user_id
        )
        return redirect("groups:detail", pk=pk)


class LeaveGroupView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, group_id: int) -> HttpResponse:
        GroupInvitationService.leave_group(
            group_id=group_id,
            user_id=request.user.id
        )
        return redirect("groups:home")


class GroupEventsCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = GroupEventCreateForm
    template_name = "groups/group-event_form.html"

    def dispatch(
            self,
            request: HttpRequest,
            *args,
            **kwargs
    ) -> HttpResponseBase:
        self.group = get_object_or_404(Group, pk=kwargs["group_id"])

        if not GroupMembership.objects.filter(
                group=self.group, user=request.user, status=Status.ACCEPTED
        ).exists():
            raise ValidationError("You are not a member of this group")

        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        kwargs["group"] = self.group
        return kwargs

    def form_valid(self, form) -> HttpResponse:
        event = form.save(commit=False)
        event.creator = self.request.user
        event.accessibility = Event.Accessibility.GROUP
        event.save()

        with transaction.atomic():
            GroupEventService.create_group_event(
                group=self.group,
                event=event,
            )
        return redirect("groups:detail", pk=self.group.id)

groups/templates/groups/components/detail_info.html
<div class="card-body">
  <h5 class="fw-semibold mb-3">Group details</h5>

  {% if group.start_date %}
    <p><strong>Start:</strong> {{ group.start_date }}</p>
  {% endif %}
  {% if group.end_date %}
    <p><strong>End:</strong> {{ group.end_date }}</p>
  {% endif %}

  <p><strong>State:</strong> {{ group.state }}</p>
  {% if current_budget %}
    <h5 class="fw-semibold mb-3">Budget overview</h5>

    <p>Current amount: {{ current_budget.current_amount }}</p>

    {% if current_budget.total_income %}
      <p>Total income: {{ current_budget.total_income }}</p>
    {% endif %}

    {% if current_budget.total_expenses %}
      <p>Total expenses: {{ current_budget.total_expenses }}</p>
    {% endif %}

    <canvas id="myBarChart" style="max-height: 360px;"></canvas>

    <script>
        const barCtx = document.getElementById("myBarChart").getContext("2d");
        new Chart(barCtx, {
            type: "bar",
            data: {
                labels: {{ chart_data.labels|safe }},
                datasets: [
                    {
                        label: "Income",
                        data: {{ chart_data.incomes|safe }},
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1,
                        borderRadius: 10,
                    },

                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    x: {
                        stacked: true,
                    },
                    y: {
                        stacked: true,
                        beginAtZero: true,
                        ticks: {
                            callback: function (value) {
                                return Math.abs(value);
                            }
                        }
                    }
                },
                plugins: {
                    tooltip: {
                        callbacks: {
                            label: function (context) {
                                let label = context.dataset.label || "";
                                if (label) {
                                    label += ": ";
                                }
                                label += Math.abs(context.parsed.y)
                                return label;
                            }
                        }
                    }
                }
            }
        });
    </script>


  {% endif %}
</div>

groups/templates/groups/components/detail_top.html
<div class="card-body">
  <div class="d-flex flex-row justify-content-center gap-2">
    <h2 class="fw-bold mb-2">{{ group.name }}</h2>
    <a class=""
       href="{% url "groups:update" pk=group.id %}">
      <svg
          width="24px" height="24px"
          viewBox="0 0 24 24" fill="#fff"
          xmlns="http://www.w3.org/2000/svg">
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g id="SVGRepo_tracerCarrier" stroke-linecap="round"
           stroke-linejoin="round" stroke="#fff"
           stroke-width="0.096"></g>
        <g id="SVGRepo_iconCarrier">
          <path fill-rule="evenodd" clip-rule="evenodd"
                d="M21.1213 2.70705C19.9497 1.53548 18.0503 1.53547 16.8787 2.70705L15.1989 4.38685L7.29289 12.2928C7.16473 12.421 7.07382 12.5816 7.02986 12.7574L6.02986 16.7574C5.94466 17.0982 6.04451 17.4587 6.29289 17.707C6.54127 17.9554 6.90176 18.0553 7.24254 17.9701L11.2425 16.9701C11.4184 16.9261 11.5789 16.8352 11.7071 16.707L19.5556 8.85857L21.2929 7.12126C22.4645 5.94969 22.4645 4.05019 21.2929 2.87862L21.1213 2.70705ZM18.2929 4.12126C18.6834 3.73074 19.3166 3.73074 19.7071 4.12126L19.8787 4.29283C20.2692 4.68336 20.2692 5.31653 19.8787 5.70705L18.8622 6.72357L17.3068 5.10738L18.2929 4.12126ZM15.8923 6.52185L17.4477 8.13804L10.4888 15.097L8.37437 15.6256L8.90296 13.5112L15.8923 6.52185ZM4 7.99994C4 7.44766 4.44772 6.99994 5 6.99994H10C10.5523 6.99994 11 6.55223 11 5.99994C11 5.44766 10.5523 4.99994 10 4.99994H5C3.34315 4.99994 2 6.34309 2 7.99994V18.9999C2 20.6568 3.34315 21.9999 5 21.9999H16C17.6569 21.9999 19 20.6568 19 18.9999V13.9999C19 13.4477 18.5523 12.9999 18 12.9999C17.4477 12.9999 17 13.4477 17 13.9999V18.9999C17 19.5522 16.5523 19.9999 16 19.9999H5C4.44772 19.9999 4 19.5522 4 18.9999V7.99994Z"
                fill="#fff"></path>
        </g>
      </svg>
    </a>
  </div>
  <p class="text-secondary">{{ group.description }}</p>

  <div class="d-flex justify-content-center flex-wrap gap-5 mt-3">
    <button class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#transactionModal">
      Add transaction
    </button>
    {% if user_role != "Member" %}
      <button class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#userKeyModal">
        Add member
      </button>
    {% endif %}
    <form
        method="post"
        action="{% url "groups:leave-group" group_id=group.id %}">
      {% csrf_token %}
      <input type="submit" value="Leave group"
             class="btn btn-danger">
    </form>
    {% if user_role == delete_permission %}
      <a class="btn btn-danger"
         href="{% url "groups:delete" pk=group.id %}">
        Delete group
      </a>
    {% endif %}
  </div>
</div>

groups/templates/groups/components/group_card.html
<a href="{% url "groups:detail" pk=group.id %}"
   class="text-decoration-none text-white">

  <div class="card bg-dark h-100 shadow-sm border-secondary event-card">
    <div
        class="card-body text-center fs-4 p-2 d-flex flex-column justify-content-between align-items-center">
      <div class="mb-3 text-success">
        {% include "groups/components/group_icon.html" with type=event.type %}
      </div>
      <h5 class="card-title fw-bold text-white fs-3 card-name">
        {{ group.name }}
      </h5>
      <p class="card-text text-secondary small fs-5 card-description">
        {{ group.description|default:"No description" }}
      </p>
      <div class="d-flex justify-content-center small text-secondary mt-3">
        <span class="badge bg-outline-secondary">
          {{ group.get_state_display }}
        </span>
      </div>
    </div>
  </div>
</a>

groups/templates/groups/components/group_connections.html
<div class="card-body">
  <h5 class="fw-semibold mb-3">Available connections</h5>

  {% if connects %}
    <ul class="list-group list-group-flush">
      {% for connect in connects %}
        <li class="list-group-item bg-dark text-white border-secondary d-flex justify-content-between align-items-center">
          <h6>{{ connect.username }}</h6>

          <form method="post"
                action="{% url "groups:invite-member" pk=group.id user_id=connect.id %}">
            {% csrf_token %}
            <button class="btn btn-info btn-sm">
              Invite
            </button>
          </form>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-secondary">No available users</p>
  {% endif %}
</div>

groups/templates/groups/components/group_members.html
<div class="card-body">
  <h5 class="fw-semibold mb-3">Members</h5>

  {% if members %}
    <ul class="list-group list-group-flush">
      {% for member in members %}
        <li class="list-group-item bg-dark text-white border-secondary">
          <h6>{{ member.user.username }}</h6>
          <p class="text-white-50">{{ member.role }}
            - {{ member.status }}</p>
          <div
              class="d-flex flex-row justify-content-center align-items-center flex-wrap gap-2 mb-2">
            {% if user_role in "Admin,Creator" and member.role in "Moderator,Member" and member.status != "Pending" %}
              <form method="post"
                    action="{% url "groups:promote" pk=group.id user_id=member.user.id %}">
                {% csrf_token %}
                <button class="btn btn-success btn-sm">
                  Promote
                </button>
              </form>
            {% endif %}
            {% if user_role in "Admin,Creator" and member.role in "Moderator,Admin" %}
              <form method="post"
                    action="{% url "groups:demote" pk=group.id user_id=member.user.id %}">
                {% csrf_token %}
                <button class="btn btn-warning btn-sm">
                  Demote
                </button>
              </form>
            {% endif %}
            {% if user_role in "Admin,Creator" and member.role != "Creator" %}
              <form method="post"
                    action="{% url "groups:reject-invite" pk=group.id user_id=member.user.id stay="inside" %}">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm">
                  Delete
                </button>
              </form>
            {% endif %}
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-secondary">No members</p>
  {% endif %}
</div>

groups/templates/groups/components/group_transactions.html
<div class="card-body">
  <h5 class="fw-semibold mb-3">Transaction history</h5>

  {% if transaction_history %}
    <ul class="list-group list-group-flush">
      {% for transaction in transaction_history %}
        <li class="list-group-item bg-dark text-white border-secondary">
          {{ transaction.get_short_description }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-secondary">No transactions yet</p>
  {% endif %}
</div>